In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import eig
from numpy.linalg import norm

In [2]:
Sx = 1/2 * np.array([[0, 1],
                     [1, 0]])
Sy = 1/2 * np.array([[0, -1j],
                     [1j, 0]])
Sz = 1/2 * np.array([[1, 0],
                     [0, -1]])
S2 =  3/4 * np.array([[1, 0],
                      [0, 1]])

In [3]:
e_vals, e_vecs = eig(S2, Sz)

Returns $\lambda$ such that

$$A\vec{s} = \lambda B \vec{s}$$

In [4]:
e_vals

array([ 1.5+0.j, -1.5+0.j])

In [5]:
Sz@e_vecs[:,0]

array([0.5, 0. ])

In [6]:
Sz_2 = np.kron(Sz, np.identity(2)) + np.kron(np.identity(2), Sz)
S2_2 = np.kron(S2, np.identity(2)) + np.kron(np.identity(2), S2)

In [14]:
e_vals, e_vecs = eig(Sz_2)

In [15]:
e_vals

array([ 1.+0.j,  0.+0.j,  0.+0.j, -1.+0.j])

In [16]:
e_vals, e_vecs = eig(S2_2)

In [17]:
e_vals

array([1.5+0.j, 1.5+0.j, 1.5+0.j, 1.5+0.j])

In [18]:
S2_2

array([[1.5, 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. ],
       [0. , 0. , 1.5, 0. ],
       [0. , 0. , 0. , 1.5]])