In [64]:
import numpy as np
import scipy as sp
from scipy.linalg import eig
from numpy.linalg import norm

In [75]:
Sx = 1/2 * np.array([[0, 1],
                     [1, 0]])
Sy = 1/2 * np.array([[0, -1j],
                     [1j, 0]])
Sz = 1/2 * np.array([[1, 0],
                     [0, -1]])
S2 =  3/4 * np.array([[1, 0],
                      [0, 1]])

In [80]:
e_vals, e_vecs = eig(S2, Sz)

Returns $\lambda$ such that

$$A\vec{s} = \lambda B \vec{s}$$

In [85]:
e_vals

array([ 1.5+0.j, -1.5+0.j])

In [84]:
Sz@e_vecs[:,0]

array([0.5, 0. ])

In [104]:
Sz_2 = np.kron(Sz, np.identity(2))
S2_2 = np.kron(S2, np.identity(2))

In [105]:
e_vals, e_vecs = eig(S2_2, Sz_2)

In [106]:
e_vecs

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [108]:
e_vals

array([ 1.5+0.j,  1.5+0.j, -1.5+0.j, -1.5+0.j])

In [99]:
Sz_2@e_vecs[:,3]

array([0., 0., 0., 1.])